language: c

sudo: false

env:
  global:
    - LLUV_PG_DBNAME=test
    - LLUV_PG_DBUSER=postgres
    - LLUV_PG_DBPASS=

matrix:
  include:
    # - env: LUA="lua 5.1"
    #   os: osx
    - env: LUA="lua 5.1"
      os: linux
    - env: LUA="lua 5.2"
      os: linux
    - env: LUA="lua 5.3"
      os: linux
    - env: LUA="luajit 2.0"
      os: linux
    - env: LUA="luajit 2.1"
      os: linux

addons:
  apt:
    packages:
      - uuid-dev 
      - unixodbc
      - unixodbc-dev
      - odbc-postgresql

services:
  - postgresql

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - gcc --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - luarocks show lluv > /dev/null 2>&1 || bash .travis/setup_uv.sh
  - psql --version
  - psql -c "create database $LLUV_PG_DBNAME;" -U postgres

install:
  - if [ "$LUA" != "lua 5.3" ]; then luarocks show struct > /dev/null 2>&1 || luarocks install struct; fi
  - luarocks show lluv > /dev/null 2>&1 || luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks make rockspecs/lluv-pg-scm-0.rockspec

before_script:
  - luarocks show lua-cjson        > /dev/null 2>&1 || luarocks install lua-cjson
  - luarocks show lua_cliargs      > /dev/null 2>&1 || luarocks install lua_cliargs 2.5
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls
  - luarocks show lluv-busted      > /dev/null 2>&1 || luarocks install lluv-busted --server=http://luarocks.org/dev
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show lua-log          > /dev/null 2>&1 || luarocks install lua-log
  - luarocks show lpeg             > /dev/null 2>&1 || luarocks install lpeg
  - luarocks show stacktraceplus   > /dev/null 2>&1 || luarocks install stacktraceplus
  - luarocks show odbc             > /dev/null 2>&1 || luarocks install odbc
  - luarocks show luasocket        > /dev/null 2>&1 || luarocks install luasocket
  # pgmoon require `bitopt` which not compatiable with Lua 5.3
  - if [ "$LUA" != "lua 5.3" ]; then luarocks show pgmoon > /dev/null 2>&1 || luarocks install pgmoon; fi

script:
  - busted_bootstrap --verbose --coverage
  - lua ./examples/perfomance.lua
  - lua ./examples/perfomance.lua

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
